include:
  - project: 'hwdesign/ci/generic_ci'
    ref: $GENERIC_CI_BRANCH
    file:
      - jobs_template.yml
  - local: 'ci/fpga_tests.yml'

image: registry.gitlab.bsc.es/hwdesign/containerhub/questa-vip:latest

## This workflow avoids duplicate pipelines when there is an open merge request (commit_branch + merge_request) 
## so only the open merge request will be executed and not the commit_branch. PIPELINE_BRANCH will be used to refer to
## CI_COMMIT_BRANCH or CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, we will not differentiate between them.
workflow:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event") # Merge requests
      variables:
        PIPELINE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - if: ($CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "pipeline") # Fix detached merge request pipelines
      when: never
    - if: ($CI_COMMIT_MESSAGE =~ /skip-ci/)
      when: never
    - if: ($CI_COMMIT_BRANCH) # All branches
      variables:
        PIPELINE_BRANCH: $CI_COMMIT_BRANCH
    - if: ($CI_PIPELINE_SOURCE == "pipeline") # trigger downstream
    - if: ($CI_COMMIT_TAG)

stages:
  - build
  - linting
  - sim_isa_tests
  - sim_benchmarks
  - sim_multicore
  - sim_mpi_mmc
  - bitstream
  - upload_bitstream
  - fpga_prepare
  - fpga_tests

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  GIT_CLEAN_FLAGS: -ffdx
  GIT_DEPTH: 1
  GIT_SUBMODULE_DEPTH: 1
  CI_RISCV_DIR: /opt/riscv-gnu-toolchain/rvv-1.0.0/
  MODELSIM_HOME: /apps/Siemens/2024.2/RHELx86/QUESTA-CORE-PRIME_2024.2
  VERILATOR_HOME: /opt/verilator/5.014
  MSM_BUILD_FLAGS: -sys=hpc -msm_build_args=+acc=n
  VLT_BUILD_FLAGS: -sys=hpc
  SIMS_FLAGS: -noclean -sim_run_args=-no_autoacc -diaglist ../piton/verif/diag/bsc_hpc_diaglist
  ASIC_FLAGS: -sarg -x_tiles=1 -y_tiles=1 -sys=hpc
  CI_TAGS: dv

default:
  tags:
    - $CI_TAGS
  before_script:
    ## Access to repos
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/".insteadOf "https://gitlab.bsc.es/"
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/".insteadOf "git@gitlab-internal.bsc.es:"
    - git config --global url."https://".insteadOf "git://"

    ## setup licenses
    - export MGLS_LICENSE_FILE=1717@epi03.bsc.es
    - export LM_LICENSE_FILE=1717@epi03.bsc.es

    ## Install missing dependencies
    - apt install -y libbit-vector-perl

    ## Setup tools
    - . /load_modulefiles_bash.sh
    - module load gcc/10.5.0
    - module load rvv/1.0.0
    - module load verilator/5.014

    ## Setup Environment
    - export RISCV=/opt/riscv-gnu-toolchain/rvv-1.0.0/
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

.rule_only_merge:
  - if: ($do_test_fpga)
    when: never
  - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/) # Merge requests, not draft 

.rules_fpga_bitstream:
  - if: ($CI_MERGE_REQUEST_TITLE =~ /Draft:/)
    when: never
  - if: ($CI_JOB_NAME =~ /bitstream/) && ( $CI_COMMIT_MESSAGE =~ /ci-test\/disable-fpga/ || 
         $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /ci-test\/disable-fpga/)
    when: never
  - if: ($BITSTREAM_URL)
    when: never
  - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /ci-test\/no-bitstream-gen/)
    when: never
  - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/) ||
        ($CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == "main") ||
        ($CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'schedule') &&
        ($do_bitstream || $CI_COMMIT_MESSAGE =~ /#do_bitstream/) ||
        ($CI_COMMIT_TAG)

.rules_default:
  - if: ($do_test_fpga)
    when: never
  - when: on_success

.rules_fpga_tests:
  - if: ($CI_JOB_NAME =~ /fpga/) && ( $CI_COMMIT_MESSAGE =~ /ci-test\/disable-fpga/ || $CI_MERGE_REQUEST_LABELS =~ /ci-test\/disable-fpga/)
    when: never
  - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/) ||
        (($CI_PIPELINE_SOURCE == 'pipeline' || $CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'schedule') && 
        ( $do_test_fpga || $CI_COMMIT_MESSAGE =~ /#do_test_fpga/)) ||
        ($CI_COMMIT_TAG)

.rules_fpga_upload:
  - if: ($CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_BRANCH == "main")
  - if: ( $do_bitstream_pkg || $CI_COMMIT_MESSAGE =~ /#do_bitstream_pkg/ )
    when: always
  - if: ($CI_COMMIT_TAG)

.regression_report:
  script:
    - regreport $(ls -td -- */ | grep -E '^([0-9_]+)/$' | head -n 1) | grep -E "^Diag" && echo " " && regreport $(ls -td -- */ | grep -E '^([0-9_]+)/$' | head -n 1) -summary && echo " "
    - regreport $(ls -td -- */ | grep -E '^([0-9_]+)/$' | head -n 1) -summary | grep "REGRESSION PASSED" && echo "Simulation PASSED" || (echo "Simulation AILED" && exit 1)

.sargantana_regression_base:
  dependencies:
    - sargantana_build
  before_script:
    - !reference [default, before_script]
    - source piton/sargantana_setup.sh
  timeout: 8h

.lox_regression_base:
  dependencies:
    - lox_build
  before_script:
    - !reference [default, before_script]
    - source piton/lox_setup.sh
  timeout: 12h

.ariane_regression_base:
  dependencies:
    - ariane_build
  before_script:
    - !reference [default, before_script]
    - source piton/ariane_setup.sh
  timeout: 8h

.ariane_hpdc_regression_base:
  dependencies:
    - ariane_hpdc_build
  before_script:
    - !reference [default, before_script]
    - source piton/ariane_setup.sh
  timeout: 8h

.vc_base:
  image: registry.gitlab.bsc.es/hwdesign/containerhub/rocky_base:latest
  tags: 
    - bm
  timeout: 2h

################################################################################
# SARGANTANA
################################################################################

sargantana_build:
  stage: build
  rules:
    !reference [.rules_default]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.sargantana_regression_base, before_script]
  script:
    - piton/sargantana_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -sarg -build_id=sargantana_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -sarg -build_id=sargantana_msm_1_1
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -sarg -build_id=sargantana_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -sarg -build_id=sargantana_msm_1_2
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_msm_2_2
    - sims -metro_mpi_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_mpi_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
      - ./piton/design/chip/tile/sargantana/simulator/reference/build/libdisasm.so
      - ./piton/design/chip/tile/sargantana/tmp/riscv-tests/build/
  
sargantana_elab_build:
  stage: build
  rules:
    !reference [.rules_default]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.sargantana_regression_base, before_script]
  script:
    - cd build
    - asic_synth $ASIC_FLAGS -asic_rtl_only
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_isa_tests:
  extends: .sargantana_regression_base
  stage: sim_isa_tests
  rules:
    !reference [.rules_default]
  needs: [sargantana_build]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=sargantana_${SIM_TYPE}_1_1
      -group=sarg_tile1_asm_tests_p
      -group=sarg_tile1_asm_tests_v
      -group=sarg_tile1_amo_tests_p
      -group=sarg_tile1_amo_tests_v
      -group=sarg_tile1_fp_tests_p
      -group=sarg_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_benchmarks:
  extends: .sargantana_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [sargantana_build, sargantana_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=sargantana_${SIM_TYPE}_1_1
      -group sarg_tile1_benchmarks
      -group sarg_tile1_mt_benchmarks
      -group sarg_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_multicore:
  extends: .sargantana_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [sargantana_build, sargantana_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=sargantana_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group sarg_tile$(($X_TILES * $Y_TILES))_simple
      -group sarg_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_mpi:
  extends: .sargantana_regression_base
  stage: sim_mpi_mmc
  rules:
    !reference [.rules_default]  
  needs: [sargantana_build]
  script:
    - cd build
    - sims -sim_type=metro_mpi $SIMS_FLAGS -build_id=sargantana_mpi_2_2
      -group sarg_tile4_simple
      -group sarg_tile4_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

################################################################################
# Lagarto Ox
################################################################################

lox_build:
  stage: build
  rules:
    !reference [.rules_default]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.lox_regression_base, before_script]
  script:
    - piton/lox_build_tools.sh $CI_JOB_TOKEN
    - cd build
    #- sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_msm_1_1
    #- sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_msm_1_2
    #- sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_msm_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
      - ./piton/design/chip/tile/lagarto_ox/simulator/reference/build/libdisasm.so
      - ./piton/design/chip/tile/lagarto_ox/tmp/riscv-tests/build/
      - ./piton/**/*.tmp.*
      - ./piton/design/chipset/**/bootrom*.sv


lox_isa_tests:
  extends: .lox_regression_base
  stage: sim_isa_tests
  rules:
    !reference [.rules_default]
  needs: [lox_build]
  parallel:
    matrix:
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=lox_${SIM_TYPE}_1_1
      -group=lox_tile1_asm_tests_p
      -group=lox_tile1_asm_tests_v
      -group=lox_tile1_amo_tests_p
      -group=lox_tile1_amo_tests_v
      -group=lox_tile1_fp_tests_p
      -group=lox_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

lox_benchmarks:
  extends: .lox_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [lox_build, lox_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=lox_${SIM_TYPE}_1_1
      -group lox_tile1_benchmarks
      -group lox_tile1_mt_benchmarks
      -group lox_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

lox_multicore:
  extends: .lox_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [lox_build, lox_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=lox_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group lox_tile$(($X_TILES * $Y_TILES))_simple
      -group lox_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

################################################################################
# ARIANE
################################################################################

ariane_build:
  stage: build
  rules:
    !reference [.rules_default]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.ariane_regression_base, before_script]
  script:
    - piton/ariane_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -build_id=ariane_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -build_id=ariane_msm_1_1
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -build_id=ariane_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -build_id=ariane_msm_1_2
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_msm_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_msm_2_2_mmc_real -multimc=2 -multimc_indices=0,3 -hbm -hbm_lat=tools/pli/Realistic_lat/curves_src/cxl.zip
    - sims -vlt_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_vlt_2_2_mmc_real -multimc=2 -multimc_indices=0,3 -hbm -hbm_lat=tools/pli/Realistic_lat/curves_src/cxl.zip
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_msm_2_2_mmc_fix  -multimc=2 -multimc_indices=1,2 -hbm -hbm_lat=100 -pronoc
    - sims -vlt_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_vlt_2_2_mmc_fix  -multimc=2 -multimc_indices=1,2 -hbm -hbm_lat=100 -pronoc   
    - sims -metro_mpi_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_mpi_2_2_mmc  -multimc=2 -multimc_indices=1,2 -hbm 
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./piton/design/chip/tile/ariane/
      - ./build

ariane_isa_tests:
  extends: .ariane_regression_base
  stage: sim_isa_tests
  rules:
    !reference [.rules_default]
  needs: [ariane_build]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_1_1
      -group ariane_tile1_asm_tests_p
      -group ariane_tile1_asm_tests_v
      -group ariane_tile1_amo_tests_p
      -group ariane_tile1_amo_tests_v
      -group ariane_tile1_fp_tests_p
      -group ariane_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_benchmarks:
  extends: .ariane_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_build, ariane_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_1_1
      -group ariane_tile1_benchmarks
      -group ariane_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_multicore:
  extends: .ariane_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_build, ariane_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
      -group ariane_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_mmc:
  extends: .ariane_regression_base
  stage: sim_mpi_mmc
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_build, ariane_multicore]
  parallel:
    matrix:
      - X_TILES: [2]
        Y_TILES: [2]
        DELAY: [fix,real]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [2]
        Y_TILES: [2]
        DELAY: [fix,real]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_${X_TILES}_${Y_TILES}_mmc_${DELAY}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build


ariane_mpi:
  extends: .ariane_regression_base
  stage: sim_mpi_mmc
  rules:
    !reference [.rules_default]
  needs: [ariane_build]  
  script:
    - cd build
    - sims -sim_type=metro_mpi $SIMS_FLAGS -build_id=ariane_mpi_2_2_mmc
      -group ariane_tile4_mmc_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
################################################################################
# ARIANE (w/ HPDC)
################################################################################

ariane_hpdc_build:
  stage: build
  rules:
    !reference [.rules_default]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.ariane_hpdc_regression_base, before_script]
  script:
    - piton/ariane_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -hpdc -build_id=ariane_hpdc_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -hpdc -build_id=ariane_hpdc_msm_1_1
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_msm_1_2
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_msm_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./piton/design/chip/tile/ariane/
      - ./build

ariane_hpdc_isa_tests:
  extends: .ariane_hpdc_regression_base
  stage: sim_isa_tests
  rules:
    !reference [.rules_default]
  needs: [ariane_hpdc_build]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_hpdc_${SIM_TYPE}_1_1
      -group ariane_tile1_asm_tests_p
      -group ariane_tile1_asm_tests_v
      -group ariane_tile1_amo_tests_p
      -group ariane_tile1_amo_tests_v
      -group ariane_tile1_fp_tests_p
      -group ariane_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_hpdc_benchmarks:
  extends: .ariane_hpdc_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_hpdc_build, ariane_hpdc_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_hpdc_${SIM_TYPE}_1_1
      -group ariane_tile1_benchmarks
      -group ariane_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_hpdc_multicore:
  extends: .ariane_hpdc_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_hpdc_build, ariane_hpdc_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_hpdc_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
      -group ariane_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

## FPGA Synthesizing bitstream FPGACLUSTER - HPC
bitstream:
  stage: bitstream
  extends:
    - .hpc_vivado_synthesis
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_PATHS: ":(exclude)piton/design/chip/tile/ariane :(exclude)piton/design/chip/tile/lagarto_ox"
    SLURM_TIME: "24:00:00"
  timeout: 24h
  parallel:
    matrix:
      - CORE: ["sarg"]
  needs: []
  rules:
    !reference [.rules_fpga_bitstream]
  script:
    - LOCAL_OUTPUT_FOLDER="bitstream_${CORE}_${CI_COMMIT_SHORT_SHA}"
    - mkdir ${LOCAL_OUTPUT_FOLDER}
    - source piton/sargantana_setup.sh
    - LD_PRELOAD=/lib64/libstdc++.so.6 protosyn --board alveou55c --design system --core ${CORE} --x_tiles 1 --y_tiles 2 --uart-dmw ddr --zeroer_off --hbm --jobs 8 --postroutephysopt --define DISABLE_SIMD,SYNTHESIZABLE_BRAM --config_l1i_size 16384 --config_l1i_associativity 4 --config_l1d_size 32768 --config_l1d_associativity 8 --config_l15_size 131072 --config_l15_associativity 8 --config_l2_size 524288 --config_l2_associativity 8 --noc1_width 64 --noc2_width 64 --noc3_width 64 --l15_num_threads 64 --l2_mshr_entries 128 --write_byte_mask
  interruptible: false
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - build/alveou55c/system/protosyn_logs/
      - build/alveou55c/system/alveou55c_system/alveou55c_system.runs/*/*.log
      - build/alveou55c/system/alveou55c_system/alveou55c_system.runs/*/*.rpt
      - build/alveou55c/system/*.log
      - build/alveou55c/system/alveou55c_system/alveou55c_system.runs/impl_1/system.bit

fpga-prepare:
  extends: .riscv
  stage: fpga_prepare
  variables:
    FPGA_TOOLS_BRANCH: main #parallel_fpga_scripts
    CORE: sarg
  needs: 
    - job: "bitstream: [sarg]"
      optional: true
  rules:
    - !reference [.rules_fpga_tests]
  script:
    # uncomment to override bsc-linux url
    #- BSC_LINUX_URL="https://gitlab.bsc.es/api/v4/projects/3441/packages/generic/zetta-tc2-ft-eth_addr4app/1.0.0/zetta-tc2-ft-eth_addr4app.tar.gz"
    - |
      if [[ "$CI_MERGE_REQUEST_LABELS" =~ ci-test/no-bitstream-gen ]] || [ ! -z ${do_test_fpga} ] && [ -z "${BITSTREAM_URL}" ]; then
        BITSTREAM_URL="https://gitlab.bsc.es/api/v4/projects/${CI_PROJECT_ID}/packages/generic/bitstream_$CORE/${CI_COMMIT_REF_SLUG}/bitstream_$CORE.tar.gz";
      fi
    - echo "BITSTREAM_URL=${BITSTREAM_URL}"
    - | 
      if [ ! -z ${BITSTREAM_URL} ]; then
        wget -nv -O bitstream.tar.gz --header "JOB-TOKEN:$CI_JOB_TOKEN" "${BITSTREAM_URL}"
        tar -xzvf bitstream.tar.gz
      fi
    - 'wget -nv -O zetta.tar.gz --header "PRIVATE-TOKEN: $BSC_LINUX_TOKEN" ${BSC_LINUX_URL}'
    - tar -xzvf zetta.tar.gz
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/hwdesign/fpga/integration-lab/fpga-tools.git -b ${FPGA_TOOLS_BRANCH} --recurse-submodules
  artifacts:
    paths:
      - fpga-tools
      - build/alveou55c/system/alveou55c_system/alveou55c_system.runs/impl_1/system.bit
      - output/images/fw_payload.*
    exclude:
      - build/debug-tests/.git

fpga-tests:
  stage: fpga_tests
  extends: 
    - .hpc_vivado_fpga
  variables:
    REPORT_PATH: reports
    SLURM_FPGAS: 8     # not used
    BOARD: "alveou55c"
    EXPECTED_RESULT: "login:"
    CLUSTER_QDMA_DRIVER_PATH: "/nfs/apps/QDMA/meep-ionic/linux-kernel/bin"
    FPGA_UART_BAUDRATE: "115200"
    CORE: sarg
  retry: 1
  needs: [fpga-prepare]
  rules:
    - !reference [.rules_fpga_tests]
  script:
    - !reference [.fpga_tests]
    - set +e
    - export BITSTREAM=build/alveou55c/system/alveou55c_system/alveou55c_system.runs/impl_1/system.bit
    - LINUX_BOOT="output/images/fw_payload.bin"
    - node=$(hostname | grep -Eo "[0-9]*")
    - host_ip=$(ifconfig | grep -Eo "10\.5\.[0-9]\.[0-9]*")
    - HOSTNAME=$(hostname)
    - echo "node=$node, hostname=${HOSTNAME}"
    - echo "BITSTREAM=${BITSTREAM}"
    # define fpga list, eventually will be given by slurm or gitlab driver
    - declare -ag fpgas
    # To adjust column width, by default it takes column name size
    - declare -A results_table_width
    - |
      if [ "$HPC_CLUSTER" == "FPGA" ]; then
        fpgas=($(seq 1 8 | xargs))
        results_table_header=("TEST_NAME" "RESULT" "PASS" "TIME" "FPGA1" "FPGA1_type" "FPGA2" "FPGA2_type" "FPGA3" "FPGA3_type" "FPGA4" "FPGA4_type" "FPGA5" "FPGA5_type" "FPGA6" "FPGA6_type" "FPGA7" "FPGA7_type" "FPGA8" "FPGA8_type")
        # Results table configuration
        results_table_width["TEST_NAME"]=37
      else
        ps -ef | grep "gitlab.*cat" | grep -v "grep" | awk '{print $2}' | xargs kill || true
        fpgas=(0)
        results_table_header=("TEST_NAME" "RESULT" "PASS" "TIME" "FPGA0" "FPGA0_type")
        results_table_width["TEST_NAME"]=60
      fi
      results_table_width["TIME"]=5
    # Export pcie drivers path in PATH or build them if not in FPGA cluster
    - |
      if [ "$HPC_CLUSTER" == "FPGA" ]; then
        export PATH=$CLUSTER_QDMA_DRIVER_PATH:$PATH
      else
        fpga-tools/fpga/build_pcie_drivers.sh
      fi
    # Load Bitstream
    - reset_result_test
    - run_sequential load_bitstream fpgas result_test
    - check_err_load_bitstream result_test
    # Set tty/UART baudrate
    - |
      for card in ${fpgas[@]}; do
        stty -F $(get_uart $node $card) $FPGA_UART_BAUDRATE raw -echo
      done
    # Run Linux tests
    - TESTS_LIST=TESTS_LIST_LINUX_${CORE}
    - run_tests_linux "${!TESTS_LIST}"
    - ps -ef | grep "gitlab.*cat" | grep -v "grep" | awk '{print $2}' | xargs kill || true
    ## RESULTS
    - merge_reports  
    - |
      {
        echo -e "\nNODE $(hostname)\n"
        results_table "$REPORT_PATH/report.yaml" results_table_header
      } | tee $REPORT_PATH/results.rpt
    - results_exit "$REPORT_PATH/report.yaml"
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ${REPORT_PATH}
      - ${TEST_FILE_NAME}
      - log.out

bitstream-upload:
  stage: upload_bitstream
  extends: .basic_no_clone
  variables:
    BITSTREAM_PATH: build/alveou55c/system/
    CORE: sarg
  needs: 
    - job: "bitstream: [sarg]"
  rules: 
    - !reference [.rules_fpga_upload]
  before_script:
    - echo "Override default before_script"
  script:
    - echo "Uploading bitstream to Package Registry..."
    - PKG_NAME="bitstream_${CORE}"
    - BRANCH_NAME=${CI_COMMIT_REF_SLUG}
    - PKG_VERSION=${BRANCH_NAME}
    - echo PACKAGE_NAME ${PKG_NAME}
    - echo PACKAGE_VERSION ${PKG_VERSION}
    - tar -zcvf ${PKG_NAME}.tar.gz $BITSTREAM_PATH
    - PKG_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PKG_NAME}/${PKG_VERSION}"
    - 'echo curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${PKG_NAME}.tar.gz ${PKG_URL}'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${PKG_NAME}.tar.gz "${PKG_URL}/${PKG_NAME}.tar.gz"'
################################################################################
# Linting
################################################################################

linting_check:
  stage: linting
  needs: [lox_build]
  extends: .vc_static
  rules:
    !reference [.rules_default]
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - cd linting_scripts
    - make FLIST=../build/hpc/lox_msm_1_1/flist VC_REL
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./linting_scripts/report


################################################################################
# DC elaboration
################################################################################

sarg_DC_elab:
  stage: linting
  rules:
    !reference [.rules_default]
  needs: [sargantana_elab_build]
  extends: .dc_shell
  script:
    - source piton/sargantana_setup.sh
    - cd build; 
    - asic_synth $ASIC_FLAGS -asic_skip_rtl_gen -asic_elaborate_only
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build



