image: registry.gitlab.bsc.es/hwdesign/containerhub/questa-vip:latest

## This workflow avoids duplicate pipelines when there is an open merge request (commit_branch + merge_request) 
## so only the open merge request will be executed and not the commit_branch. PIPELINE_BRANCH will be used to refer to
## CI_COMMIT_BRANCH or CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, we will not differentiate between them.
workflow:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event") # Merge requests
      variables:
        PIPELINE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - if: ($CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "pipeline") # Fix detached merge request pipelines
      when: never
    - if: ($CI_COMMIT_MESSAGE =~ /skip-ci/)
      when: never
    - if: ($CI_COMMIT_BRANCH) # All branches
      variables:
        PIPELINE_BRANCH: $CI_COMMIT_BRANCH
    - if: ($CI_PIPELINE_SOURCE == "pipeline") # trigger downstream
    - if: ($CI_COMMIT_TAG)

stages:
  - build
  - sim_isa_tests
  - sim_benchmarks
  - sim_multicore
  - sim_mpi_mmc
  - linting

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  GIT_CLEAN_FLAGS: -ffdx
  GIT_DEPTH: 1
  GIT_SUBMODULE_DEPTH: 1
  CI_RISCV_DIR: /opt/riscv-gnu-toolchain/rvv-1.0.0/
  MODELSIM_HOME: /apps/Siemens/2024.2/RHELx86/QUESTA-CORE-PRIME_2024.2
  VERILATOR_HOME: /opt/verilator/5.014
  MSM_BUILD_FLAGS: -sys=hpc -msm_build_args=+acc=n
  VLT_BUILD_FLAGS: -sys=hpc
  SIMS_FLAGS: -noclean -sim_run_args=-no_autoacc -diaglist ../piton/verif/diag/bsc_hpc_diaglist
  ASIC_FLAGS: -sarg -x_tiles=1 -y_tiles=1 -sys=hpc
  CI_TAGS: dv

default:
  tags:
    - $CI_TAGS
  before_script:
    ## Access to repos
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/".insteadOf "https://gitlab.bsc.es/"
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/".insteadOf "git@gitlab-internal.bsc.es:"
    - git config --global url."https://".insteadOf "git://"

    ## setup licenses
    - export MGLS_LICENSE_FILE=1717@epi03.bsc.es
    - export LM_LICENSE_FILE=1717@epi03.bsc.es

    ## Install missing dependencies
    - apt install -y libbit-vector-perl

    ## Setup tools
    - . /load_modulefiles_bash.sh
    - module load gcc/10.5.0
    - module load rvv/1.0.0
    - module load verilator/5.014

    ## Setup Environment
    - export RISCV=/opt/riscv-gnu-toolchain/rvv-1.0.0/
    - export OMPI_ALLOW_RUN_AS_ROOT=1
    - export OMPI_ALLOW_RUN_AS_ROOT_CONFIRM=1

.rule_only_merge:
  - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/) # Merge requests, not draft 

.regression_report:
  script:
    - regreport $(ls -td -- */ | grep -E '^([0-9_]+)/$' | head -n 1) | grep -E "^Diag" && echo " " && regreport $(ls -td -- */ | grep -E '^([0-9_]+)/$' | head -n 1) -summary && echo " "
    - regreport $(ls -td -- */ | grep -E '^([0-9_]+)/$' | head -n 1) -summary | grep "REGRESSION PASSED" && echo "Simulation PASSED" || (echo "Simulation AILED" && exit 1)

.sargantana_regression_base:
  dependencies:
    - sargantana_build
  before_script:
    - !reference [default, before_script]
    - source piton/sargantana_setup.sh
  timeout: 8h

.lox_regression_base:
  dependencies:
    - lox_build
  before_script:
    - !reference [default, before_script]
    - source piton/lox_setup.sh
  timeout: 10h
.ariane_regression_base:
  dependencies:
    - ariane_build
  before_script:
    - !reference [default, before_script]
    - source piton/ariane_setup.sh
  timeout: 8h

.ariane_hpdc_regression_base:
  dependencies:
    - ariane_hpdc_build
  before_script:
    - !reference [default, before_script]
    - source piton/ariane_setup.sh
  timeout: 8h

.vc_base:
  image: registry.gitlab.bsc.es/hwdesign/containerhub/rocky_base:latest
  tags: 
    - bm
  timeout: 2h

################################################################################
# SARGANTANA
################################################################################

sargantana_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.sargantana_regression_base, before_script]
  script:
    - piton/sargantana_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -sarg -build_id=sargantana_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -sarg -build_id=sargantana_msm_1_1
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -sarg -build_id=sargantana_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -sarg -build_id=sargantana_msm_1_2
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_msm_2_2
    - sims -metro_mpi_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_mpi_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
      - ./piton/design/chip/tile/sargantana/simulator/reference/build/libdisasm.so
      - ./piton/design/chip/tile/sargantana/tmp/riscv-tests/build/
  
sargantana_elab_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.sargantana_regression_base, before_script]
  script:
    - cd build
    - asic_synth $ASIC_FLAGS -asic_rtl_only
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_isa_tests:
  extends: .sargantana_regression_base
  stage: sim_isa_tests
  needs: [sargantana_build]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=sargantana_${SIM_TYPE}_1_1
      -group=sarg_tile1_asm_tests_p
      -group=sarg_tile1_asm_tests_v
      -group=sarg_tile1_amo_tests_p
      -group=sarg_tile1_amo_tests_v
      -group=sarg_tile1_fp_tests_p
      -group=sarg_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_benchmarks:
  extends: .sargantana_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [sargantana_build, sargantana_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=sargantana_${SIM_TYPE}_1_1
      -group sarg_tile1_benchmarks
      -group sarg_tile1_mt_benchmarks
      -group sarg_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_multicore:
  extends: .sargantana_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [sargantana_build, sargantana_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=sargantana_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group sarg_tile$(($X_TILES * $Y_TILES))_simple
      -group sarg_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_mpi:
  extends: .sargantana_regression_base
  stage: sim_mpi_mmc
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/
    - if: $CI_COMMIT_BRANCH   # run also for normal commits
  needs: [sargantana_build]
  script:
    - cd build
    - sims -sim_type=metro_mpi $SIMS_FLAGS -build_id=sargantana_mpi_2_2
      -group sarg_tile4_simple
      -group sarg_tile4_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

################################################################################
# Lagarto Ox
################################################################################

lox_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.lox_regression_base, before_script]
  script:
    - piton/lox_build_tools.sh $CI_JOB_TOKEN
    - cd build
    #- sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_msm_1_1
    #- sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_msm_1_2
    #- sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -lox -config_rtl=OX_EXCLUDE_VPU -build_id=lox_msm_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
      - ./piton/design/chip/tile/lagarto_ox/simulator/reference/build/libdisasm.so
      - ./piton/design/chip/tile/lagarto_ox/tmp/riscv-tests/build/
      - ./piton/**/*.tmp.*
      - ./piton/design/chipset/**/bootrom*.sv


lox_isa_tests:
  extends: .lox_regression_base
  stage: sim_isa_tests
  needs: [lox_build]
  parallel:
    matrix:
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=lox_${SIM_TYPE}_1_1
      -group=lox_tile1_asm_tests_p
      -group=lox_tile1_asm_tests_v
      -group=lox_tile1_amo_tests_p
      -group=lox_tile1_amo_tests_v
      -group=lox_tile1_fp_tests_p
      -group=lox_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

lox_benchmarks:
  extends: .lox_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [lox_build, lox_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=lox_${SIM_TYPE}_1_1
      -group lox_tile1_benchmarks
      -group lox_tile1_mt_benchmarks
      -group lox_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

lox_multicore:
  extends: .lox_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [lox_build, lox_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=lox_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group lox_tile$(($X_TILES * $Y_TILES))_simple
      -group lox_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

################################################################################
# ARIANE
################################################################################

ariane_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.ariane_regression_base, before_script]
  script:
    - piton/ariane_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -build_id=ariane_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -build_id=ariane_msm_1_1
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -build_id=ariane_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -build_id=ariane_msm_1_2
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_msm_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_msm_2_2_mmc_real -multimc=2 -multimc_indices=0,3 -hbm -hbm_lat=tools/pli/Realistic_lat/curves_src/cxl.zip
    - sims -vlt_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_vlt_2_2_mmc_real -multimc=2 -multimc_indices=0,3 -hbm -hbm_lat=tools/pli/Realistic_lat/curves_src/cxl.zip
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_msm_2_2_mmc_fix  -multimc=2 -multimc_indices=1,2 -hbm -hbm_lat=100 -pronoc
    - sims -vlt_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_vlt_2_2_mmc_fix  -multimc=2 -multimc_indices=1,2 -hbm -hbm_lat=100 -pronoc   
    - sims -metro_mpi_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_mpi_2_2_mmc  -multimc=2 -multimc_indices=1,2 -hbm 
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./piton/design/chip/tile/ariane/
      - ./build

ariane_isa_tests:
  extends: .ariane_regression_base
  stage: sim_isa_tests
  needs: [ariane_build]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_1_1
      -group ariane_tile1_asm_tests_p
      -group ariane_tile1_asm_tests_v
      -group ariane_tile1_amo_tests_p
      -group ariane_tile1_amo_tests_v
      -group ariane_tile1_fp_tests_p
      -group ariane_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_benchmarks:
  extends: .ariane_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_build, ariane_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_1_1
      -group ariane_tile1_benchmarks
      -group ariane_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_multicore:
  extends: .ariane_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_build, ariane_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
      -group ariane_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_mmc:
  extends: .ariane_regression_base
  stage: sim_mpi_mmc
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_build, ariane_multicore]
  parallel:
    matrix:
      - X_TILES: [2]
        Y_TILES: [2]
        DELAY: [fix,real]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [2]
        Y_TILES: [2]
        DELAY: [fix,real]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_${SIM_TYPE}_${X_TILES}_${Y_TILES}_mmc_${DELAY}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build


ariane_mpi:
  extends: .ariane_regression_base
  stage: sim_mpi_mmc
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/
    - if: $CI_COMMIT_BRANCH   # run also for normal commits
  needs: [ariane_build]  
  script:
    - cd build
    - sims -sim_type=metro_mpi $SIMS_FLAGS -build_id=ariane_mpi_2_2_mmc
      -group ariane_tile4_mmc_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
################################################################################
# ARIANE (w/ HPDC)
################################################################################

ariane_hpdc_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    CI_TAGS: non_resources
  before_script:
    - !reference [.ariane_hpdc_regression_base, before_script]
  script:
    - piton/ariane_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -hpdc -build_id=ariane_hpdc_vlt_1_1
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=1 -ariane -hpdc -build_id=ariane_hpdc_msm_1_1
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_vlt_1_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=1 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_msm_1_2
    - sims -vlt_build $VLT_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_vlt_2_2
    - sims -msm_build $MSM_BUILD_FLAGS -x_tiles=2 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_msm_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./piton/design/chip/tile/ariane/
      - ./build

ariane_hpdc_isa_tests:
  extends: .ariane_hpdc_regression_base
  stage: sim_isa_tests
  needs: [ariane_hpdc_build]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_hpdc_${SIM_TYPE}_1_1
      -group ariane_tile1_asm_tests_p
      -group ariane_tile1_asm_tests_v
      -group ariane_tile1_amo_tests_p
      -group ariane_tile1_amo_tests_v
      -group ariane_tile1_fp_tests_p
      -group ariane_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_hpdc_benchmarks:
  extends: .ariane_hpdc_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_hpdc_build, ariane_hpdc_isa_tests]
  parallel:
    matrix:
      - SIM_TYPE: vlt
        CI_TAGS: non_resources
      - SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_hpdc_${SIM_TYPE}_1_1
      -group ariane_tile1_benchmarks
      -group ariane_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_hpdc_multicore:
  extends: .ariane_hpdc_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  needs: [ariane_hpdc_build, ariane_hpdc_benchmarks]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: vlt
        CI_TAGS: non_resources
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE: msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE $SIMS_FLAGS -build_id=ariane_hpdc_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
      -group ariane_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

################################################################################
# Linting
################################################################################

linting_check:
  stage: linting
  needs: [lox_build]
  extends: .vc_base
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - export SNPS_LICENSE_FILE=27020@epi01.bsc.es
    - export SNPSLMD_LICENSE_FILE=27020@epi01.bsc.es
    - export LM_LICENSE_FILE=$LM_LICENSE_FILE:$SNPS_LICENSE_FILE:$SNPSLMD_LICENSE_FILE
    - export SNPSLMD_QUEUE=true
    - source /eda/synopsys/synopsys.sh
    - source piton/lox_setup.sh
  script:
    - cd linting_scripts
    - make FLIST=../build/hpc/lox_msm_1_1/flist VC_REL
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./linting_scripts/report


################################################################################
# DC elaboration
################################################################################

sarg_DC_elab:
  stage: linting
  needs: [sargantana_elab_build]
  extends: .vc_base
  before_script:
    - export SNPS_LICENSE_FILE=27020@epi01.bsc.es
    - export SNPSLMD_LICENSE_FILE=27020@epi01.bsc.es
    - export LM_LICENSE_FILE=$LM_LICENSE_FILE:$SNPS_LICENSE_FILE:$SNPSLMD_LICENSE_FILE
    - export SNPSLMD_QUEUE=true
    - export RISCV=/opt/riscv-gnu-toolchain/rvv-1.0.0/
    - source /eda/synopsys/synopsys.sh
    - source piton/sargantana_setup.sh
  script:
    - cd build; 
    - asic_synth $ASIC_FLAGS -asic_skip_rtl_gen -asic_elaborate_only
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build



