image: registry.gitlab.bsc.es/hwdesign/containerhub/questa_riscv:latest

## This workflow avoids duplicate pipelines when there is an open merge request (commit_branch + merge_request) 
## so only the open merge request will be executed and not the commit_branch. PIPELINE_BRANCH will be used to refer to
## CI_COMMIT_BRANCH or CI_MERGE_REQUEST_SOURCE_BRANCH_NAME, we will not differentiate between them.
workflow:
  rules:
    - if: ($CI_PIPELINE_SOURCE == "merge_request_event") # Merge requests
      variables:
        PIPELINE_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    - if: ($CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "schedule" && $CI_PIPELINE_SOURCE != "pipeline") # Fix detached merge request pipelines
      when: never
    - if: ($CI_COMMIT_MESSAGE =~ /skip-ci/)
      when: never
    - if: ($CI_COMMIT_BRANCH) # All branches
      variables:
        PIPELINE_BRANCH: $CI_COMMIT_BRANCH
    - if: ($CI_PIPELINE_SOURCE == "pipeline") # trigger downstream
    - if: ($CI_COMMIT_TAG)

stages:
  - build
  - sim_isa_tests
  - sim_benchmarks
  - sim_multicore

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: none
  GIT_CLEAN_FLAGS: -ffdx
  GIT_DEPTH: 1
  GIT_SUBMODULE_DEPTH: 1
  CI_RISCV_DIR: /opt/riscv-gnu-toolchain/rvv-0.7.1/
  MODELSIM_HOME: /eda/Siemens/2022-23/RHELx86/QUESTA-CORE-PRIME_2022.4
  VERILATOR_HOME: /opt/verilator/5.014

default:
  tags:
    - dv
  before_script:
    ## Access to repos
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/".insteadOf "https://gitlab.bsc.es/"
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.bsc.es/".insteadOf "git@gitlab-internal.bsc.es:"
    - git config --global url."https://".insteadOf "git://"

    ## setup licenses
    - export MGLS_LICENSE_FILE=1717@epi03.bsc.es
    - export LM_LICENSE_FILE=1717@epi03.bsc.es

    ## Install missing dependencies
    - apt install -y libbit-vector-perl

    ## Setup tools
    - . /load_modulefiles_bash.sh
    - module load gcc/10.5.0
    - module load rvv/0.7.1
    - module load verilator/5.014

.rule_only_merge:
  - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /Draft:/) # Merge requests, not draft 

.regression_report:
  script:
    - regreport $(ls -td -- */ | head -n 1) | grep -E "^Diag" && echo " " && regreport $(ls -td -- */ | head -n 1) -summary && echo " "
    - regreport $(ls -td -- */ | head -n 1) -summary | grep "REGRESSION PASSED" && echo "Simulation PASSED" || (echo "Simulation AILED" && exit 1)

.sargantana_regression_base:
  dependencies:
    - sargantana_build
  before_script:
    - !reference [default, before_script]
    - module swap rvv/1.0.0 # Sargantana implements RVV 1.0
    - source piton/sargantana_setup.sh
    - export VERILATOR_ROOT=/opt/verilator/5.014
  timeout: 4h

.ariane_regression_base:
  dependencies:
    - ariane_build
  before_script:
    - !reference [default, before_script]
    - source piton/ariane_setup.sh
    - export RISCV=/opt/riscv-gnu-toolchain/rvv-0.7.1/
    - export VERILATOR_ROOT=/opt/verilator/5.014
  timeout: 4h

.ariane_hpdc_regression_base:
  dependencies:
    - ariane_hpdc_build
  before_script:
    - !reference [default, before_script]
    - source piton/ariane_setup.sh
    - export RISCV=/opt/riscv-gnu-toolchain/rvv-0.7.1/
    - export VERILATOR_ROOT=/opt/verilator/5.014
  timeout: 4h

################################################################################
# SARGANTANA
################################################################################

sargantana_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - !reference [.sargantana_regression_base, before_script]
  script:
    - piton/sargantana_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build -sys=manycore -x_tiles=1 -y_tiles=1 -sarg -build_id=sargantana_vlt_1_1
    - sims -msm_build -sys=manycore -x_tiles=1 -y_tiles=1 -sarg -build_id=sargantana_msm_1_1
    - sims -vlt_build -sys=manycore -x_tiles=1 -y_tiles=2 -sarg -build_id=sargantana_vlt_1_2
    - sims -msm_build -sys=manycore -x_tiles=1 -y_tiles=2 -sarg -build_id=sargantana_msm_1_2
    - sims -vlt_build -sys=manycore -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_vlt_2_2
    - sims -msm_build -sys=manycore -x_tiles=2 -y_tiles=2 -sarg -build_id=sargantana_msm_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
      - ./piton/design/chip/tile/sargantana/simulator/reference/build/libdisasm.so
      - ./piton/design/chip/tile/sargantana/tmp/riscv-tests/build/

sargantana_isa_tests:
  extends: .sargantana_regression_base
  stage: sim_isa_tests
  parallel:
    matrix:
      - SIM_TYPE:
        - vlt
        - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=sargantana_${SIM_TYPE}_1_1
      -group=sarg_tile1_asm_tests_p
      -group=sarg_tile1_asm_tests_v
      -group=sarg_tile1_amo_tests_p
      -group=sarg_tile1_amo_tests_v
      -group=sarg_tile1_fp_tests_p
      -group=sarg_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_benchmarks:
  extends: .sargantana_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  parallel:
    matrix:
      - SIM_TYPE:
        - vlt
        - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=sargantana_${SIM_TYPE}_1_1
      -group sarg_tile1_benchmarks
      -group sarg_tile1_mt_benchmarks
      -group sarg_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

sargantana_multicore:
  extends: .sargantana_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE:
          - vlt
          - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=sargantana_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group sarg_tile$(($X_TILES * $Y_TILES))_simple
      -group sarg_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

################################################################################
# ARIANE
################################################################################

ariane_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - !reference [.ariane_regression_base, before_script]
  script:
    - piton/ariane_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build -sys=manycore -x_tiles=1 -y_tiles=1 -ariane -build_id=ariane_vlt_1_1
    - sims -msm_build -sys=manycore -x_tiles=1 -y_tiles=1 -ariane -build_id=ariane_msm_1_1
    - sims -vlt_build -sys=manycore -x_tiles=1 -y_tiles=2 -ariane -build_id=ariane_vlt_1_2
    - sims -msm_build -sys=manycore -x_tiles=1 -y_tiles=2 -ariane -build_id=ariane_msm_1_2
    - sims -vlt_build -sys=manycore -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_vlt_2_2
    - sims -msm_build -sys=manycore -x_tiles=2 -y_tiles=2 -ariane -build_id=ariane_msm_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./piton/design/chip/tile/ariane/
      - ./build

ariane_isa_tests:
  extends: .ariane_regression_base
  stage: sim_isa_tests
  parallel:
    matrix:
      - SIM_TYPE:
        - vlt
        - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=ariane_${SIM_TYPE}_1_1
      -group ariane_tile1_asm_tests_p
      -group ariane_tile1_asm_tests_v
      -group ariane_tile1_amo_tests_p
      -group ariane_tile1_amo_tests_v
      -group ariane_tile1_fp_tests_p
      -group ariane_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_benchmarks:
  extends: .ariane_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  parallel:
    matrix:
      - SIM_TYPE:
        - vlt
        - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=ariane_${SIM_TYPE}_1_1
      -group ariane_tile1_benchmarks
      -group ariane_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_multicore:
  extends: .ariane_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE:
          - vlt
          - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=ariane_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
      -group ariane_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build


################################################################################
# ARIANE (w/ HPDC)
################################################################################

ariane_hpdc_build:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - !reference [.ariane_hpdc_regression_base, before_script]
  script:
    - piton/ariane_build_tools.sh $CI_JOB_TOKEN
    - cd build
    - sims -vlt_build -sys=manycore -x_tiles=1 -y_tiles=1 -ariane -hpdc -build_id=ariane_hpdc_vlt_1_1
    - sims -msm_build -sys=manycore -x_tiles=1 -y_tiles=1 -ariane -hpdc -build_id=ariane_hpdc_msm_1_1
    - sims -vlt_build -sys=manycore -x_tiles=1 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_vlt_1_2
    - sims -msm_build -sys=manycore -x_tiles=1 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_msm_1_2
    - sims -vlt_build -sys=manycore -x_tiles=2 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_vlt_2_2
    - sims -msm_build -sys=manycore -x_tiles=2 -y_tiles=2 -ariane -hpdc -build_id=ariane_hpdc_msm_2_2
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./piton/design/chip/tile/ariane/
      - ./build

ariane_hpdc_isa_tests:
  extends: .ariane_hpdc_regression_base
  stage: sim_isa_tests
  parallel:
    matrix:
      - SIM_TYPE:
        - vlt
        - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=ariane_hpdc_${SIM_TYPE}_1_1
      -group ariane_tile1_asm_tests_p
      -group ariane_tile1_asm_tests_v
      -group ariane_tile1_amo_tests_p
      -group ariane_tile1_amo_tests_v
      -group ariane_tile1_fp_tests_p
      -group ariane_tile1_fp_tests_v
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_hpdc_benchmarks:
  extends: .ariane_hpdc_regression_base
  stage: sim_benchmarks
  rules:
    !reference [.rule_only_merge]
  parallel:
    matrix:
      - SIM_TYPE:
        - vlt
        - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=ariane_hpdc_${SIM_TYPE}_1_1
      -group ariane_tile1_benchmarks
      -group ariane_tile1_simple
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build

ariane_hpdc_multicore:
  extends: .ariane_hpdc_regression_base
  stage: sim_multicore
  rules:
    !reference [.rule_only_merge]
  parallel:
    matrix:
      - X_TILES: [1,2]
        Y_TILES: [2]
        SIM_TYPE:
          - vlt
          - msm
  script:
    - cd build
    - sims -sim_type=$SIM_TYPE -noclean -build_id=ariane_hpdc_${SIM_TYPE}_${X_TILES}_${Y_TILES}
      -group ariane_tile$(($X_TILES * $Y_TILES))_simple
      -group ariane_tile$(($X_TILES * $Y_TILES))_mt_benchmarks
    - !reference [.regression_report, script]
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - ./build
