set lint_script_dir $env(LINT_SCRIPT_DIR)
set report_dir $env(REPORT_DIR)
set uncore_dir $env(UNCORE_MERGED_DIR)

set DESIGN cmp_top

set file_path $lint_script_dir/uncore/filelist_merge
set file [open $file_path "r"]
set names_list {}

while {[gets $file name] != -1} {
    lappend names_list $name
}

close $file

# Waivers (awl or tcl):
sg_read_waiver -file $lint_script_dir/cincoranch_lint_intel_waiver.awl
source $lint_script_dir/uncore_vc_lint_waiver.tcl
sg_read_waiver -file $lint_script_dir/exclude_nonuncore_autogenerated.awl
source $lint_script_dir/cincoranch_lint_intel_waiver.tcl

set_app_var search_path "$uncore_dir/modules $uncore_dir/include $uncore_dir/include/axi"
set_app_var enable_lint true

# Reading Intel linting rules 
source $lint_script_dir/lint_rules.tcl

analyze -format sverilog "$names_list"
elaborate $DESIGN

#read_sdc $constraints_path

check_lint
report_lint -verbose -limit 10000 -file $report_dir/linting_report.txt
report_lint