waive_violation -app Lint -status Waived -add uncore1 -tag "W164a_a" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*lruarray_write_data_s3\[`L15_LRUARRAY_RR_MASK\] = lru_data_s3\[`L15_LRUARRAY_RR_MASK\].*" } -ignore -regex -comment {"It is due to the pointer increment by 1"}
waive_violation -app Lint -status Waived -add uncore2 -tag "W164a_a" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*csm_ticket_s2 = \{threadid_s2, mshr_type_s2\}.*" } -ignore -regex -comment {"NO_RTL_CSM is defined in our design so CSM signals are ignored"}
waive_violation -app Lint -status Waived -add uncore3 -tag "W164a_a" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*write_mask_s1 = \(offset_mask_s1\[.\]\).*" } -ignore -regex -comment {"L15_BYTE_MASK_WIDHT = 64, so this if is not executed."}
waive_violation -app Lint -status Waived -add uncore4 -tag "ImproperRangeIndex-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*lru_used_bits_s2\[lru_round_robin_turn_s2 \+ `L15_WAY_WIDTH.*" } -ignore -regex -comment {"it is correct, if overflow MSBs are ignored"}
waive_violation -app Lint -status Waived -add uncore5 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*mshr_pipe_readres_control_s1.*" } -ignore -regex -comment {"Bit 14 is not used"}
waive_violation -app Lint -status Waived -add uncore6 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*noc2decoder_l15_address.*" } -ignore -regex -comment {"middle bits are handled inside the code"}
waive_violation -app Lint -status Waived -add uncore7 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*cache_index_l1d_s.*" } -ignore -regex -comment {"due to PITON_ARIANE_HPDC define these signals are not used"}
waive_violation -app Lint -status Waived -add uncore8 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*tagcheck_state_(s|e)_s3.*" } -ignore -regex -comment {"the signal is unused"}
waive_violation -app Lint -status Waived -add uncore9 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*tagcheck_state_s_s2.*" } -ignore -regex -comment {"the signal is unused"}
waive_violation -app Lint -status Waived -add uncore10 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*predecode_mshr_read_control_s1.*" } -ignore -regex -comment {"Bit 14 is not used"}
waive_violation -app Lint -status Waived -add uncore11 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*predecode_mshr_read_homeid_s1.*" } -ignore -regex -comment {"signal is unused due to the defines"}
waive_violation -app Lint -status Waived -add uncore12 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*dcache_data.*" } -ignore -regex -comment {"due to PARALLEL_SRAMS define dcache_data is not used"}
waive_violation -app Lint -status Waived -add uncore13 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*lru_way_s3_bypassed.*" } -ignore -regex -comment {"the signal is unused"}
waive_violation -app Lint -status Waived -add uncore14 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*dtag_tag_way_s2\[.\].*" } -ignore -regex -comment {"due to cach size only L15_CACHE_TAG_WIDTH lower bits are needed"}
waive_violation -app Lint -status Waived -add uncore15 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*stbuf_way_s3.*" } -ignore -regex -comment {"due to PITON_ARIANE_HPDC define this signal is not used"}
waive_violation -app Lint -status Waived -add uncore16 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*creditman_noc1_avail_next = creditman_noc1_add2 \? creditman_noc1_avail \+ 2.*" } -ignore -regex -comment {"width mismatch is due to sum which is ok"}
waive_violation -app Lint -status Waived -add uncore17 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*lru_way_s2 = lru_round_robin_turn_s2 \+ ..*" } -ignore -regex -comment {"width mismatch is due to sum which is ok"}
waive_violation -app Lint -status Waived -add uncore18 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*cache_subline_s2 <= cache_subline_s2 \+ 1.*" } -ignore -regex -comment {"width mismatch is due to sum which is ok"}
waive_violation -app Lint -status Waived -add uncore19 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*l15_dtag_write_mask_s1 = l15_dtag_write_mask_s1 <<.*" } -ignore -regex -comment {"the shift value is never more than l15_dtag_write_mask_s1 bits. dtag_write_way_s1 does not go more than 8 but it requires 4 bits to store 8, so linting expects it may reach 15 which wont."}
waive_violation -app Lint -status Waived -add uncore20 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*stall_tmp_result = stall_tmp_operand1 – stall_tmp_operand2.*" } -ignore -regex -comment {"it is a minus of 2 positive numbers in which first one is bigger than second one so overflow never happens"}
waive_violation -app Lint -status Waived -add uncore21 -tag "W192" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*begin" } -ignore -regex -comment {"nothing should happen in that state, or never happens"}
waive_violation -app Lint -status Waived -add uncore22 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l15.v" ) AND Statement =~ "*\) pipeline\(*" } -ignore -regex -comment {"The 2 least significant bits are intentionally ignored when PARALLEL_SRAMS is defined"}
waive_violation -app Lint -status Waived -add uncore23 -tag "UndrivenNUnloaded-ML" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*begin.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore24 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*l2_mshr_wrap mshr_wrap\(.*" } -ignore -regex -comment {"This signal in unused in l2 module. However if NO_L2_CAM_MSHR is defined, which is not, there is a width mismatch for this signal in l2_mshr module"}
waive_violation -app Lint -status Waived -add uncore25 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*l2_config_regs config_regs\(.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is NOT defined. It is defined for us."}
waive_violation -app Lint -status Waived -add uncore26 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*\) pipe2 \(.*" } -ignore -regex -comment {"This signal is only used when NO_L2_CAM_MSHR is defined. Which is not."}
waive_violation -app Lint -status Waived -add uncore27 -tag "W287b" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*\.pdata_out \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore28 -tag "W287b" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*\.csm_en \(\).*" } -ignore -regex -comment {"This signal is connected only when NO_RTL_CSM is NOT defined. It is defined for us."}
waive_violation -app Lint -status Waived -add uncore29 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*l2_decoder decoder\(.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore30 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.msg_subline_vector \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore31 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.l2_ifill_64B_S2 \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore32 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.msg_subline_id \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore33 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.msg_last_subline \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore34 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.inv_fwd_pending \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore35 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.msg_mesi \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore36 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.inv_fwd_pending \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore37 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.smc_miss_out \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore38 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*\.msg_l2_miss \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore39 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*dir_data_out.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore40 -tag "W240" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*dir_data_out.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore41 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*l2_mshr_decoder mshr_decoder.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore42 -tag "W287b" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*\.msg_amo_mask \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore43 -tag "W287b" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*\.msg_l2_miss \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore44 -tag "W287b" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*\.msg_subline_vector \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore45 -tag "W287b" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*\.amo_mask_out \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore46 -tag "W287b" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*\.smc_miss_out \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore47 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*addr_S.*" } -ignore -regex -comment {"The 6 lower bits are not used, as it only requires tag bits"}
waive_violation -app Lint -status Waived -add uncore48 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*pipe2_addr_S.*" } -ignore -regex -comment {"The 6 lower bits are not used, as it only requires tag bits"}
waive_violation -app Lint -status Waived -add uncore49 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*addr_l2_aligned_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore50 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_l2_miss_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore51 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_data_size_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore52 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_subline_S2.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore53 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*lsid_S4.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore54 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*addr_S4.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore55 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*mshr_miss_lsid_S4.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore56 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*addr_op_S. = addr_S..*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore57 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cs_S2 = \{.*" } -ignore -regex -comment {"Bits 26~23 are not used"}
waive_violation -app Lint -status Waived -add uncore58 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*mshr_pending_index_S4_f.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore59 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*l2_priority_encoder_6 priority_encoder_6bits.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore60 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*dir_sharer_counter_S4_next = dir_sharer_counter_S4_f \+ 1.*" } -ignore -regex -comment {"width mismatch is due to sum which is ok"}
waive_violation -app Lint -status Waived -add uncore61 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_tag_hit_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore62 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_sel_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore63 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*lsid_S2.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore64 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_vd_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore65 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*addr_l2_aligned_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore66 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*mshr_msg_type_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore67 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_wb_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore68 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*addr_S..*" } -ignore -regex -comment {"All bits are not used, as it only requires tag bits"}
waive_violation -app Lint -status Waived -add uncore69 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_cache_type_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore70 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*is_same_address_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore71 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*msg_from_mshr_S3_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore72 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*msg_mesi_S2_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore73 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_addr_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore74 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*valid_S4.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore75 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_mshrid_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore76 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_recycled_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore77 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_(sd|ls)id_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore78 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*dir_data_S4.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore79 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*stall_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore80 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*smt_base_addr.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore81 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_amo_mask_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore82 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*valid_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore83 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*msg_from_mshr_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore84 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*msg_data_ready_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore85 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*stall_before_S3.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore86 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_src_y_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore87 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_src_fbits_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore88 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_src_chipid_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore89 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*mshr_way_S2_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore90 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*data_data_shift_S4.*" } -ignore -regex -comment {"only upper 32 or 64 bits are used"}
waive_violation -app Lint -status Waived -add uncore91 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*data_data_shift_S4.*" } -ignore -regex -comment {"only upper 32 or 64 bits of the signal are needed"}
waive_violation -app Lint -status Waived -add uncore92 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*state_rb_S2 = l2_rb_bits_S2 \+ 1.*" } -ignore -regex -comment {"width mismatch is due to sum which is ok"}
waive_violation -app Lint -status Waived -add uncore93 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*data_data_mask_in_S2.*" } -ignore -regex -comment {"width mismatch is due to a shift left, which is ok"}
waive_violation -app Lint -status Waived -add uncore94 -tag "W287b" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*\.data_out_mask \(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore95 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*valid_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore96 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*valid_S3.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore97 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*msg_type_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore98 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*stall_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore99 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*state_data_trans_S2.*" } -ignore -regex -comment {"Only specific bits are used depending on parameters"}
waive_violation -app Lint -status Waived -add uncore100 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*mshr_miss_lsid_S3_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore101 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*src_fbits_S2_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore102 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*src_x_S2_f .*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore103 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*mshrid_S3_f .*" } -ignore -regex -comment {"only L2_MSHR_INDEX_WIDTH lower bits are used"}
waive_violation -app Lint -status Waived -add uncore104 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*src_chipid_S2_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore105 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*src_y_S2_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore106 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_read_ticket.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore107 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_hmt_base_reg.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore108 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*system_tile_count.*" } -ignore -regex -comment {"only HOME_ID_BITS (6) are needed"}
waive_violation -app Lint -status Waived -add uncore109 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*noc1encoder_csm_req_ack.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore110 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*diag_en_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore111 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*flush_en_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore112 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_clump_sel_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore113 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*rd_en_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore114 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*wr_en_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore115 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_y_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore116 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*ghid_ticketed_cache.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore117 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*ghid_ticketed_cache_val.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore118 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*addr_in_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore119 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_req_address_s3.*" } -ignore -regex -comment {"only specific bits are needed."}
waive_violation -app Lint -status Waived -add uncore120 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*mshr_pipe_readres_homeid_s1.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore121 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*msg_send_type_pre_S4.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore122 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_src_(x|y)_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore123 -tag "UndrivenNUnloaded-ML" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*pdata_out *\(\).*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore124 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*mshr_rd_en *\(mshr_rd_en_p2\).*" } -ignore -regex -comment {"This signal is only used when NO_L2_CAM_MSHR is defined. Which is not."}
waive_violation -app Lint -status Waived -add uncore125 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_amo_alu.v" ) AND Statement =~ ".*address.*" } -ignore -regex -comment {"Only 4 lower bits are needed"}
waive_violation -app Lint -status Waived -add uncore126 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_data.v" ) AND Statement =~ ".*addr.*" } -ignore -regex -comment {"when PARALLEL_SRAMS is defined 2 lowe bits are not neede"}
waive_violation -app Lint -status Waived -add uncore127 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_data.v" ) AND Statement =~ ".*data_mask_in.*" } -ignore -regex -comment {"only specific bits are needed."}
waive_violation -app Lint -status Waived -add uncore128 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "noc2decoder.v" ) AND Statement =~ ".*noc2_data.*" } -ignore -regex -comment {"only specific bits are needed."}
waive_violation -app Lint -status Waived -add uncore129 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_data_ecc.tmp.v" ) AND Statement =~ ".*parity.*" } -ignore -regex -comment {"MSB is not used"}
waive_violation -app Lint -status Waived -add uncore130 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "sram_l15_data.v" ) AND Statement =~ ".*BW.*" } -ignore -regex -comment {"only specific bits are needed."}
waive_violation -app Lint -status Waived -add uncore131 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "noc1buffer.tmp.v" ) AND Statement =~ ".*l15_noc1buffer_req_csm_data.*" } -ignore -regex -comment {"only lower 16 bits are used"}
waive_violation -app Lint -status Waived -add uncore132 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*l15_noc3encoder_req_fwdack_vector.*" } -ignore -regex -comment {"LSB is not used"}
waive_violation -app Lint -status Waived -add uncore133 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*mshr_l2_miss_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore134 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*lsid_S2.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore135 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_msg_type_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore136 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_owner_S4.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore137 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_cache_type_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore138 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cs_S4.*" } -ignore -regex -comment {"MSB is not used"}
waive_violation -app Lint -status Waived -add uncore139 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*mshr_mshrid_S1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore140 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*data_size_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore141 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*data_in_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore142 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_x_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore143 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_req_clump_id_s3.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore144 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_chipid_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore145 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_req_ticket_s3.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
waive_violation -app Lint -status Waived -add uncore146 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_buf_in.tmp.v" ) AND Statement =~ ".*header_buf_empty.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore147 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_buf_in.tmp.v" ) AND Statement =~ ".*msg_data_state_next_middle.*" } -ignore -regex -comment {"Only 2 lower bits are usd."}
waive_violation -app Lint -status Waived -add uncore148 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_buf_in.tmp.v" ) AND Statement =~ ".*msg_header_in.*" } -ignore -regex -comment {"Bit usage depends on parameter NOC_DATA_WIDTH."}
waive_violation -app Lint -status Waived -add uncore149 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_buf_in.tmp.v" ) AND Statement =~ ".*data_wr_ptr_f_plus1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore150 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_buf_out.tmp.v" ) AND Statement =~ ".*buf_empty.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore151 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe1_buf_out.tmp.v" ) AND Statement =~ ".*buf_full.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore152 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_buf_in.tmp.v" ) AND Statement =~ ".*data_rd_ptr_plus1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore153 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_buf_in.tmp.v" ) AND Statement =~ ".*header_rd_ptr_next_middle.*" } -ignore -regex -comment {"only L2_P2_HEADER_BUF_IN_LOG_SIZE (=2) lower bits are used"}
waive_violation -app Lint -status Waived -add uncore154 -tag "UnloadedNet-ML" -filter { ( FileName =~ "l2_pipe2_buf_in.tmp.v" ) AND Statement =~ ".*data_buf_can_get_1.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore155 -tag "UnloadedNet-ML" -filter { ( FileName =~ "simplenocbuffer" ) AND Statement =~ ".*msg_tmp.*" } -ignore -regex -comment {"bits usage depends on parameters"}
waive_violation -app Lint -status Waived -add uncore156 -tag "UnloadedNet-ML" -filter { ( FileName =~ "dmbr.tmp.v" ) AND Statement =~ ".*stall.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore157 -tag "UnloadedNet-ML" -filter { ( FileName =~ "valrdy_to_credit.v" ) AND Statement =~ ".*is_one_f.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore158 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "noc_extractSize.v" ) AND Statement =~ ".*header.*" } -ignore -regex -comment {"only specific bits are needed."}
waive_violation -app Lint -status Waived -add uncore159 -tag "UnloadedNet-ML" -filter { ( FileName =~ "dynamic_output_top.v" ) AND Statement =~ ".*current_route_req.*" } -ignore -regex -comment {"This signal is used only when KILL_HEADERS is 1. In our case is set to 0"}
waive_violation -app Lint -status Waived -add uncore160 -tag "UnloadedNet-ML" -filter { ( FileName =~ "dynamic_output_top.v" ) AND Statement =~ ".*data_out_len_zero.*" } -ignore -regex -comment {"This signal is used only when KILL_HEADERS is 1. In our case is set to 0"}
waive_violation -app Lint -status Waived -add uncore161 -tag "UnloadedNet-ML" -filter { ( FileName =~ "dynamic_output_top.v" ) AND Statement =~ ".*data_out_memory_ack_user_bits_set.*" } -ignore -regex -comment {"This signal is used only when KILL_HEADERS is 1. In our case is set to 0"}
waive_violation -app Lint -status Waived -add uncore162 -tag "UnloadedNet-ML" -filter { ( FileName =~ "dynamic_output_top.v" ) AND Statement =~ ".*length_in.*" } -ignore -regex -comment {"bit [1:0] of the length is not used as we have increased the NoC_width"}
waive_violation -app Lint -status Waived -add uncore163 -tag "UnloadedNet-ML" -filter { ( FileName =~ "dynamic_input_top_4.v" ) AND Statement =~ ".*length_in.*" } -ignore -regex -comment {"bit [1:0] of the length is not used as we have increased the NoC_width"}
waive_violation -app Lint -status Waived -add uncore164 -tag "UnloadedNet-ML" -filter { ( FileName =~ "dynamic_input_top_16.v" ) AND Statement =~ ".*length_in.*" } -ignore -regex -comment {"bit [1:0] of the length is not used as we have increased the NoC_width"}
waive_violation -app Lint -status Waived -add uncore165 -tag "UnloadedOutTerm-ML" -filter { ( FileName =~ "dynamic_input_top_4.v" ) AND Statement =~ ".*data_internal.*" } -ignore -regex -comment {"This signal is douplication of data_out for internal use. Only specefic bits are used. "}
waive_violation -app Lint -status Waived -add uncore166 -tag "W164a_a" -filter { ( FileName =~ "noc2decoder.v" ) AND Statement =~ ".*dmbr_l2_miss_mshrid_next.*" } -ignore -regex -comment {"DMBR module not used, depends on MSHR parameter"}
waive_violation -app Lint -status Waived -add uncore167 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*NOC3_WORDS_NUM.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore168 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "valrdy_to_credit.v" ) AND Statement =~ ".*BUFFER_SIZE.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore169 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*BUFFER_WIDTH.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore170 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "noc_width_adaptor.v" ) AND Statement =~ ".*INPUT_WIDTH.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore171 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "valrdy_to_credit.v" ) AND Statement =~ ".*BUFFER_SIZE.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore172 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "noc1encoder.v" ) AND Statement =~ ".*NOC_WIDTH.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore173 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*NOC_WIDTH.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore174 -tag "UnloadedNet-ML" -filter { ( FileName =~ "simplenocbuffer.v" ) AND Statement =~ ".*msg_tmp.*" } -ignore -regex -comment {"Depends on parameter"}
waive_violation -app Lint -status Waived -add uncore175 -tag "W164a_b" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*flit_state_next - data_ptr.*" } -ignore -regex -comment {"Harmless carry bit, guarded by if condition"}
waive_violation -app Lint -status Waived -add uncore176 -tag "W164a_b" -filter { ( FileName =~ "valrdy_to_credit.v" ) AND Statement =~ ".*count_f \+ 1'b1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore177 -tag "W164a_b" -filter { ( FileName =~ "noc1buffer.tmp.v" ) AND Statement =~ ".*data_rdindex \+ 1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore178 -tag "W164a_b" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*flit_state.*\+ i.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore179 -tag "W164a_b" -filter { ( FileName =~ "simplenocbuffer.v" ) AND Statement =~ ".*len_captured + CHANEL_OUT_SIZE.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore180 -tag "W164a_b" -filter { ( FileName =~ "simplenocbuffer.v" ) AND Statement =~ ".*index \+ 1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore181 -tag "W164a_b" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*flit_state \+ NOC3_WORDS_NUM.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore182 -tag "W164a_b" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*assign ptr_plus_i.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore183 -tag "W164a_b" -filter { ( FileName =~ "noc_width_adaptor.v" ) AND Statement =~ ".*counter\+1'b1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore184 -tag "W164a_b" -filter { ( FileName =~ "noc1buffer.tmp.v" ) AND Statement =~ ".*data_wrindex \+ 1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore185 -tag "W164a_b" -filter { ( FileName =~ "noc1encoder.v" ) AND Statement =~ ".*flit_state \+ 4.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore186 -tag "W164a_b" -filter { ( FileName =~ "noc1buffer.tmp.v" ) AND Statement =~ ".*command_wrindex \+ 1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore187 -tag "W164a_b" -filter { ( FileName =~ "noc1buffer.tmp.v" ) AND Statement =~ ".*command_rdindex \+ 1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore188 -tag "W240" -filter { ( FileName =~ "noc2decoder.v" ) AND Statement =~ ".*noc2_data.*" } -ignore -regex -comment {"Not all fields need to be decoded"}
waive_violation -app Lint -status Waived -add uncore189 -tag "W240" -filter { ( FileName =~ "noc1buffer.tmp.v" ) AND Statement =~ ".*l15_noc1buffer_req_csm_data.*" } -ignore -regex -comment {"Not all fields need to be decoded"}
waive_violation -app Lint -status Waived -add uncore190 -tag "W240" -filter { ( FileName =~ "noc3encoder.v" ) AND Statement =~ ".*l15_noc3encoder_req_fwdack_vector.*" } -ignore -regex -comment {"Last bit ignored as optimization"}
waive_violation -app Lint -status Waived -add uncore191 -tag "W287b" -filter { ( FileName =~ "credit_to_valrdy.v" ) AND Statement =~ ".*data_val1.*" } -ignore -regex -comment {"Not needed"}
waive_violation -app Lint -status Waived -add uncore192 -tag "W287b" -filter { ( FileName =~ "noc_width_adaptor.v" ) AND Statement =~ ".*is_header.*" } -ignore -regex -comment {"Not needed"}
waive_violation -app Lint -status Waived -add uncore193 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*L15_L1D_LINE_SIZE\s*==.*" } -ignore -regex -comment {"No problem, it is to make the code generic with defining parameter"}
waive_violation -app Lint -status Waived -add uncore194 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*l15_noc1buffer_req_size.*" } -ignore -regex -comment {"No problem, it is to make the code generic with defining parameter"}
waive_violation -app Lint -status Waived -add uncore195 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*`L15_BYTE_MASK_WIDHT\s*==.*" } -ignore -regex -comment {"No problem, it is to make the code generic with defining parameter"}
waive_violation -app Lint -status Waived -add uncore196 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*L15_REQ_DATA_WIDTH\s*==.*" } -ignore -regex -comment {"No problem, it is to make the code generic with defining parameter"}
waive_violation -app Lint -status Waived -add uncore197 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*stall_tmp_result = stall_tmp_operand1 \- stall_tmp_operand2.*" } -ignore -regex -comment {"lRHS will never have more bits than LHS"}
waive_violation -app Lint -status Waived -add uncore198 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*creditman_noc1_data_avail_next.*" } -ignore -regex -comment {"width mismatch is due to sum which is ok"}
waive_violation -app Lint -status Waived -add uncore199 -tag "W164a_b" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*creditman_noc1_reserve_next.*" } -ignore -regex -comment {"width mismatch is due to sum which is ok"}
waive_violation -app Lint -status Waived -add uncore200 -tag "W175" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*L15_WMT_ALIAS_HI.*" } -ignore -regex -comment {"It is used only when PITON_ARIANE_HPDC in not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore201 -tag "W175" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*L15_WMT_WIDTH.*" } -ignore -regex -comment {"It is used only when PITON_ARIANE_HPDC in not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore202 -tag "W240" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*pcxdecoder_l15_data_next_entry.*" } -ignore -regex -comment {"It is used when L15_REQ_DATA_WIDTH = 64, which is 512 in our case"}
waive_violation -app Lint -status Waived -add uncore203 -tag "W240" -filter { ( FileName =~ "l15_pipeline.tmp.v" ) AND Statement =~ ".*noc2decoder_l15_address.*" } -ignore -regex -comment {"only bits 0 to 3 are used"}
waive_violation -app Lint -status Waived -add uncore204 -tag "W164a_b" -filter { ( FileName =~ "l2_mshr_wrap.tmp.v" ) AND Statement =~ ".*empty_slots \+ 1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore205 -tag "W164a_b" -filter { ( FileName =~ "l2_mshr_wrap.tmp.v" ) AND Statement =~ ".*wbg_counter_f \+ 1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore206 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "l2_pipe2_buf_in.tmp.v" ) AND Statement =~ ".*L15_L1D_LINE_SIZE\s*==.*" } -ignore -regex -comment {"No problem, it is to make the code generic with defining parameter"}
waive_violation -app Lint -status Waived -add uncore207 -tag "W164a_b" -filter { ( FileName =~ "l2_mshr_wrap.tmp.v" ) AND Statement =~ ".*counter_mem_f\s*\[\s*wr_index_in\s*\]\s*\+\s*1.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore208 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_buf_in.tmp.v" ) AND Statement =~ ".*header_wr_ptr_next\s*=\s*\(.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore209 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_buf_in.tmp.v" ) AND Statement =~ ".*_f\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore210 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_buf_out.tmp.v" ) AND Statement =~ ".*_f\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore211 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe2_buf_in.tmp.v" ) AND Statement =~ ".*_f\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore212 -tag "W164a_b" -filter { ( FileName =~ "l2_config_regs.v" ) AND Statement =~ ".*_f\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore213 -tag "W164a_b" -filter { ( FileName =~ "l2_amo_alu.v" ) AND Statement =~ ".*operand_a\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore214 -tag "W164a_b" -filter { ( FileName =~ "l2_config_regs.v" ) AND Statement =~ ".*_subline\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore215 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_buf_out.tmp.v" ) AND Statement =~ ".*rd_ptr_incr\s*=.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore216 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*_S2\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore217 -tag "W164a_b" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*_S2\s*\+.*" } -ignore -regex -comment {"Harmless carry bit"}
waive_violation -app Lint -status Waived -add uncore218 -tag "W240" -filter { ( FileName =~ "l2_data.v" ) AND Statement =~ ".*(deepsleep|pdout_en|addr).*" } -ignore -regex -comment {"These port are not used or used partially"}
waive_violation -app Lint -status Waived -add uncore219 -tag "W240" -filter { ( FileName =~ "l2_data.v" ) AND Statement =~ ".*data_mask.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore220 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*cam_mshr_.*" } -ignore -regex -comment {"These port are not used or used partially"}
waive_violation -app Lint -status Waived -add uncore221 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*(stall|valid)_.*" } -ignore -regex -comment {"These ports are not used"}
waive_violation -app Lint -status Waived -add uncore222 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*dir_op_S2.*" } -ignore -regex -comment {"The port range is used partially."}
waive_violation -app Lint -status Waived -add uncore223 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*dir_data_S4.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore224 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*smt_base_addr.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore225 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*msg_data_ready_S2.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore226 -tag "W240" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*(stall|valid)_.*" } -ignore -regex -comment {"These signals are not used"}
waive_violation -app Lint -status Waived -add uncore227 -tag "W240" -filter { ( FileName =~ "l2_pipe2_dpath.tmp.v" ) AND Statement =~ ".*(data|mshr|msg)_.*" } -ignore -regex -comment {"These port are not used or used partially"}
waive_violation -app Lint -status Waived -add uncore228 -tag "W240" -filter { ( FileName =~ "l2_dir.v" ) AND Statement =~ ".*(deepsleep|pdout_en).*" } -ignore -regex -comment {"Thses ports are not used"}
waive_violation -app Lint -status Waived -add uncore229 -tag "W240" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_hmt_base_reg.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore230 -tag "W240" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*l15_csm_read_ticket.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore231 -tag "W240" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*noc1encoder_csm_req_ack.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore232 -tag "W240" -filter { ( FileName =~ "l15_csm.tmp.v" ) AND Statement =~ ".*system_tile_count.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore233 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*addr_S.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore234 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*mshr_miss_lsid_S4.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore235 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*pipe2_addr_S.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore236 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_msg_type_S1.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore237 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_l2_miss_S1.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore238 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_owner_S4.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore239 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_data_size_S1.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore240 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*addr_l2_aligned_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore241 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*pipe2_addr_S2.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore242 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*cam_mshr_cache_type_S1.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore243 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_subline_S2.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore244 -tag "W240" -filter { ( FileName =~ "l2_state.tmp.v" ) AND Statement =~ ".*(deepsleep|pdout_en).*" } -ignore -regex -comment {"These ports are not used"}
waive_violation -app Lint -status Waived -add uncore245 -tag "W240" -filter { ( FileName =~ "l2_tag.v" ) AND Statement =~ ".*(deepsleep|pdout_en).*" } -ignore -regex -comment {"These ports are not used"}
waive_violation -app Lint -status Waived -add uncore246 -tag "W240" -filter { ( FileName =~ "l2_amo_alu.v" ) AND Statement =~ ".*address.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore247 -tag "W240" -filter { ( FileName =~ "l2_data_ecc.tmp.v" ) AND Statement =~ ".*parity.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore248 -tag "W240" -filter { ( FileName =~ "l2_decoder.v" ) AND Statement =~ ".*msg_header.*" } -ignore -regex -comment {"only specific bits are used"}
waive_violation -app Lint -status Waived -add uncore249 -tag "W241" -filter { ( FileName =~ "l2_data.v" ) AND Statement =~ ".*pdata_out.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore250 -tag "W241" -filter { ( FileName =~ "l2_tag.v" ) AND Statement =~ ".*pdata_out.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore251 -tag "W241" -filter { ( FileName =~ "l2_state.tmp.v" ) AND Statement =~ ".*pdata_out.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore252 -tag "W241" -filter { ( FileName =~ "l2_dir.v" ) AND Statement =~ ".*pdata_out.*" } -ignore -regex -comment {"This signal is not used"}
waive_violation -app Lint -status Waived -add uncore253 -tag "W287b" -filter { ( FileName =~ "l2.v" ) AND Statement =~ ".*(pdata_out|csm_en).*" } -ignore -regex -comment {"These signals are  not used"}
waive_violation -app Lint -status Waived -add uncore254 -tag "W287b" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*data_out_mask.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore255 -tag "W287b" -filter { ( FileName =~ "l2_pipe2.v" ) AND Statement =~ ".*(amo_mask|_miss).*" } -ignore -regex -comment {"These signals are  not used"}
waive_violation -app Lint -status Waived -add uncore256 -tag "W287b" -filter { ( FileName =~ "l2_pipe1.v" ) AND Statement =~ ".*(_miss|msg_|ifill_|inv_).*" } -ignore -regex -comment {"These signals are  not used"}
waive_violation -app Lint -status Waived -add uncore257 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*addr_l2_aligned_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore258 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*is_same_address_S1.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore259 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_wb_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore260 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*mshr_msg_type_S1.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore261 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*mshr_l2_miss_S1.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore262 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_sel_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore263 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_tag_hit_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore264 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_cache_type_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore265 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*addr_S(3|1).*" } -ignore -regex -comment {"only tag bits are used"}
waive_violation -app Lint -status Waived -add uncore266 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*lsid_S2.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore267 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*addr_S2.*" } -ignore -regex -comment {"only data bits are used"}
waive_violation -app Lint -status Waived -add uncore268 -tag "W240" -filter { ( FileName =~ "l2_pipe2_ctrl.tmp.v" ) AND Statement =~ ".*l2_way_state_vd_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore269 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*msg_from_mshr_S2.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore270 -tag "UnloadedInPort-ML" -filter { ( FileName =~ "l2_decoder.v" ) AND Statement =~ ".*msg_header.*" } -ignore -regex -comment {"Unloaded bits are not used"}
waive_violation -app Lint -status Waived -add uncore271 -tag "W240" -filter { ( FileName =~ "l2_pipe1_ctrl.tmp.v" ) AND Statement =~ ".*lsid_S.*" } -ignore -regex -comment {"It is used only when NO_RTL_CSM is not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore272 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "l2_pipe2_buf_in.tmp.v" ) AND Statement =~ ".*data_rd_ptr_inc\s*=.*" } -ignore -regex -comment {"No problem, it is to make the code generic with defining parameter"}
waive_violation -app Lint -status Waived -add uncore273 -tag "AlwaysFalseTrueCond-ML" -filter { ( FileName =~ "l2_data.v" ) AND Statement =~ ".*L2_DATA_ECC_DATA_WIDTH.*" } -ignore -regex -comment {"No problem, it is to make the code generic with defining parameter"}
waive_violation -app Lint -status Waived -add uncore274 -tag "W175" -filter { ( FileName =~ "l15.v" ) AND Statement =~ ".*L15_WMT_WIDTH.*" } -ignore -regex -comment {"It is used only when PITON_ARIANE_HPDC in not defined. Which is defined in our case"}
waive_violation -app Lint -status Waived -add uncore275 -tag "W240" -filter { ( FileName =~ "sram_l15_data.v" ) AND Statement =~ ".*BW.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore276 -tag "W240" -filter { ( FileName =~ "sram_l15_data.v" ) AND Statement =~ ".*SRAMID.*" } -ignore -regex -comment {"this signal is not used"}
waive_violation -app Lint -status Waived -add uncore277 -tag "W240" -filter { ( FileName =~ "l2_pipe1_dpath.tmp.v" ) AND Statement =~ ".*msg_send_type_pre_S4.*" } -ignore -regex -comment {"This signal is only used when NO_RTL_CSM is not defined. It is defined in our case."}
